org: wesleycoderre
app: c3-serverless-app
service: c3-serverless

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get